Algoritmo "senha_fixa"
// Professor: Nelio Alves 
// Autor(a): Yohanan Aguilar Amaral
// Data atual: 01/12/2025
Var
// Seção de Declarações das variáveis 
   senha: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Digite a senha: ")
   Leia(senha)
   
   Enquanto (senha <> 2002) faca
      Escreva("Senha Inválida! Tente novamente: ")
      Leia(senha)
   Fimenquanto

   Escreva("Acesso permitido")
Fimalgoritmo