Algoritmo "sequencia_impares"
// Professor: Nelio Alves
// Autor(a): Yohanan Aguilar Amaral
// Data atual: 11/12/2025
Var
// Seção de Declarações das variáveis 
   i, X: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Digite o valor de X: ")
   Leia(X)
   
   Para i de 1 ate X faca
      Se (i % 2 <> 0) entao
         Escreval(i)
      Fimse
   Fimpara
Fimalgoritmo