Algoritmo "soma"
// Professor   : Nelio Alves
// Autor(a)    : Yohanan Aguilar Amaral
// Data atual  : 22/10/2025
Var
// Seção de Declarações das variáveis 
   valorX, valorY, soma: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Digite o valor de X: ")
   leia(valorX)
   
   Escreva("Digite o valor de Y: ")
   leia(valorY)
   
   soma <- valorX + valorY
   
   Escreva("SOMA = ", soma)
Fimalgoritmo